# requirements
- respond to commands
- send Sounds when a sound command is sent
- listen to channel, auto play order sound, when certain number of people are speaking

--- # Commands
- order / ordah: One random Sound out of the Order Array 
- botinfo: Bot Info
- commands: List of Commands
- zen: Play 'Zen' Sound
- flamingo: Play 'Flying Flamingo' Sounds
- join: 
- leave: 